@extends('layouts.main')

@section('content')
<section class="py-5 bg-light">
    <div class="container">
    <p>
        Terms of Use<br><br>
        Last Updated on 10 March 2026<br><br>

        In terms of Information Technology Act, 2000, this document is an electronic record. Being generated by a computer system it does not require any physical or digital signature. This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of the website www.Dharadhan.com<br><br>
        This website, www.Dharadhan.com, (hereinafter referred to as "Dharadhan") is owned, hosted and operated by Dharadhan Ventures Private Limited) (hereinafter referred to as DHARADHAN), a company incorporated in India under the Companies Act, 2013 and having its registered office at Khasra No.274/126,Ramsinghpura Urf Rampura, Mansarovar Jaipur – 302 020, For the purpose of these Terms of Use, wherever the context so requires "You" or "User" shall mean any legitimate person who is viewing/browsing the Website and/or has agreed to avail the Services provided through the Website by providing the required information while registering on the Website. The term "We", "Us", "Our", "Dharadhan", "DD" used in these Terms shall mean Dharadhan Ventures Private Limited).<br><br>

        <b>1. ACCEPTANCE TO TERMS OF USE</b><br><br>

        The use of this Website by You is solely governed by these Terms of Use ("Terms" or "Terms of Use") and any policy/terms so mentioned by terms of reference. Browsing the Website or use of the services offered through the Website shall be taken to mean that You have read and agreed to Terms of Use so binding in You and that You are contracting with Dharadhan and have undertaken binding obligations with Dharadhan. By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by Privacy Policy available at /privacy-policy, which may be amended from time to time.<br><br>

        You will be subject to the rules, guidelines, policies, terms, and conditions applicable to any service that is provided by this Website, and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part of Terms of Use.<br><br>

        <b>2. AMENDMENT/MODIFICATION OF TERMS/SERVICES</b><br><br>

        We hold the sole right to modify the Terms of Use without prior permission from You or informing You. The relationship creates on You, a duty to periodically check these Terms and stay updated on its requirements. If You continue to browse/use the Website following such a change, this is deemed as consent by You to the so amended policies.
        Dharadhan, reserves its right to withdraw wholly or partly, without assigning any reason, any of Services offered through the Website with or without any notice.<br><br>

        <b>3. SCOPE OF SERVICES</b><br><br>

        DHARADHAN offers an array of online services including but not limited to advertising or listing of properties on the website for sale, lease, purchase, creating a network for an apartment complex/building whereby. You can interact with your neighbours, apartment complex accounting, registration of society, posting classified advertisements, services offered by various third party vendors ("Services"). The services offered by Dharadhan / third party vendors may be availed by both individuals and organizations such as builders, developers or brokers. You are permitted to post your requirements / advertisements on our website as long as such posting is genuine and is in accordance with the Terms. Further, with your consent, You may authorize any person, including Dharadhan, to carry out the postings on your behalf and such postings shall also be in accordance with the Terms. You shall be solely liable for any posting done by you or by any person on your behalf or with your consent.<br><br>

        <b>4. REGISTRATION OBLIGATION AND MEMBERSHIP</b><br><br>

        In order to avail the various services offered by us, you are required to register with Dharadhan. If you represent an organization and wish to use the Services for your organization, we recommend that You, and all other users from your organization, sign up for user accounts by providing your corporate contact information. The membership of this website is available only to those above the age of 18 barring those Incompetent to Contract™ which inter alias include insolvents and the same is not allowed to minors as described by the Indian Contract Act, 1872. If you are a minor and wish to browse/use the Website, you may do so through your legal guardian and Dharadhan reserves the right to terminate your account on knowledge of You being a minor and using the membership of the Website.<br>
        Further, you are solely responsible for protecting the confidentiality of your username and password and any activity under the account will be deemed to have been done by you. You agree to: a) provide true, accurate, current and complete information about yourself as prompted by the sign up process; and b) maintain and promptly update the information provided during sign up to keep it true, accurate, current, and complete. In the event you provide us with false and inaccurate details or Dharadhan has a valid reason to believe that false and inaccurate information has been furnished, we hold the rights to permanently suspend your account and levy penalty (esp. for brokers who list as owners or builders providing fake info).<br><br>

        <b>5. PAYMENT OBLIGATION</b><br><br>

        The charges/fees for the various Services offered by Dharadhan have been clearly set forth in the Website. There are both paid services and free services offered through the Website. The details of the Services that are offered without charges and with charges are clearly set out in Website or You may communicate with us at sales@Dharadhan.com to get more information. You understand that the Services offered without any charges are restricted (as per the information you may have obtained from DD or as may be seen while availing the said Services). Hence You may be required to pay the amounts, communicated by us or set forth in the Website, if you wish to avail any Services other than the free Services offered. Dharadhan reserves the right to alter/modify the amounts payable for the Services without any prior notice. The details of cancellation and refund are provided in /public-pages/cancellation-and-refund. There will be no refund of any amounts paid by you for availing the various Services offered through the Website, except expressly stated elsewhere Dharadhan may offer certain discounts or other offers for the various Services. The terms and conditions of the offers/discounts shall be clearly set forth in the Website and the same may be time bound and hence you may not claim any offers/discounts when the time for the same has lapsed/expired. There are specific services which are offered directly by third party vendors and the role of DD in such cases is only to post the availability of such services on our website. DD will not be liable or responsible in any way for such services or the quality of such services. Any payments being made by Users do not accrue to DD and DD will not entertain any requests for information / clarification regarding such Services.<br><br>

        <b>6. REGULATION OF USAGE OF WEBSITE:</b><br><br>

        The User agrees and undertakes not to reverse engineer, modify, copy, distribute, transmit, display, perform, reproduce, publish, license, create derivative works from, transfer, or sell any information or software obtained from the Website.
        You agree not to use the Website (including, without limitation, any Services you may obtain through your use of the Website):<br><br>

        •	in a manner that violates any local, state, national, foreign, or international statute,<br>
            regulation, rule, order, treaty, or other law;<br>
        •	to stalk, harass, or harm another individual or organization;<br>
        •	to impersonate any person or entity or otherwise misrepresent your affiliation with a 
            person or entity;<br>
        •	to interfere with or disrupt the Website or servers or networks connected to the Website.<br><br>

        Without limiting the foregoing, you may not list or sell any prohibited / banned items in the Market Place.<br>
        You agree not to submit any property descriptions, photographs, financial, contact or other information contained in each Property's data to the Website unless You have acquired received all necessary rights and authorizations from the owner of such property or the power-of-attorney holder, including from the photographer and/or copyright owner of any photographs, to publish and advertise the said property(s) on the Website. Photographs with any watermark are prohibited.<br><br>

        <b>7. TERMINATION OF REGISTRATION:</b><br><br>

        Without limiting any other remedies, Dharadhan may terminate your account if 
        (a) you are found or suspected to have engaged in fraudulent activity in connection with the use of our Services,<br>
        (b) we are of the opinion that you have breached these Terms or such other reasons as deemed fit by Dharadhan with or without assigning any reasons/evidence thereof.<br><br>

        <b>8. COMMUNICATION FROM DHARADHAN:</b><br><br>

        As part of the Services offered to registered members, we may need to communicate with you via e-mail (see our Privacy Policy to learn more about communications). You agree to receive e-mails which are specific to your account and necessary for the normal functioning of the Services, including one or more welcome e-mails which help inform new users about various features of the Services. By becoming a registered member of Dharadhan and/or using the Services, you agree to receive certain communication from Dharadhan. You hereby confirm that, you do not have any objection to receiving emails, messages (SMS or any other mode) calls from Dharadhan, its group companies, affiliates and subsidiaries. This consent shall supersede any preferences set by you with or registration done with the Do Not Disturb (DND Register)/ National Customer Preference Register (NCPR).
        We may also send Residents occasional e-mail bulletins encouraging them to log in to the Network or take advantage of various features or offers, unless such Residents have opted not to receive these e-mails. These e-mails may also contain neighbourhood information, tips and suggestions or any other offer provided by third party. Dharadhan does not take any responsibility of the validity of any of these offers. If we make these e-mails available to Residents in your Network, you will be able to opt in or out of these e-mails at any time by updating your preferences through your "Settings" page.<br><br>

        <b>9. Information for Users/Service Providers:</b><br><br>

        Because certain areas of the Website are designed to help Users discover new rental or purchasing opportunities, you may browse some sections of the Network for any apartment complex/building on the Website, even if you have not yet registered. However, you will not be able to read or post any reviews or ratings in these sections unless you have logged in as a Resident of that Network's building. Dharadhan will not make available any of the information which could be private to any apartment to public users without notifying users of the network. However authority of deciding upon a piece of information to be private stays with Dharadhan.<br><br>

        <b>10. INTELLECTUAL PROPERTY RIGHTS</b><br><br>

        All logos, brands, trademarks and service marks ("Marks") appearing in Website are the properties either owned or used under license by Dharadhan. All rights accruing from the same, statutory or otherwise, wholly vest with Dharadhan. The access to this Website does not confer upon you any license or right to use in respect of these Marks and therefore the use of these Marks in any form or manner, whatsoever is strictly prohibited. Any violation of the above would constitute an offence under the prevailing laws of India.
        Dharadhan respects the Intellectual Property Rights of all, it has and will continue to adhere to all the laws applicable in India in this respect. Dharadhan shall respect the Intellectual Property Rights of the users as well as third parties. In a case where a User/s are found to be using Website as a platform to infringe the Intellectual Property Rights of others, Dharadhan will be free to terminate the said User/s account forthwith without any notice to the user.<br><br>

        <b>11. PRIVACY POLICY</b><br><br>

        The user of Dharadhan is subject to Dharadhan Privacy Policy .<br><br>

        <b>12. DISCLIAMER</b><br><br>

        The user of Dharadhan is subject to Dharadhan Disclaimer.<br><br>

        <b>13. WHISTLEBLOWING</b><br><br>

        Dharadhan reserves the right to publish property details with Your consent that have been furnished by You. However, should there be a situation where Your consent was not obtained, You would be required to contact Dharadhan immediately. Discussing this on any public or social forum is prohibited and a legal penalty will be applicable if this is found. Any feedback regarding correction of details has to be communicated to Dharadhan immediately. Dharadhan can be contacted on info@Dharadhan.com or sales@Dharadhan.com or on +91-________________ or at Our office address Dharadhan Ventures Private Limited, Khasra No.274/126,Ramsinghpura Urf Rampura, Mansarovar Jaipur – 302 020, Rajasthan, India, <br><br>

        <b>14. NO LIABILITY</b><br><br>

        Unless explicitly stated in any part of the Website, we are not involved in the actual transactions between buyers and sellers of any goods or services or any users posting any information/listings on the Website. We absolutely have no control over the quality, safety or legality of the items or services advertised, the truth or accuracy of the listings, the ability of sellers to sell items or the ability of buyers to buy items offered thorough the Website. We cannot and do not controls whether or not sellers will complete the sale of items they offer or buyers will complete the purchase of items they have committed to buy. In addition, note that there are risks of dealing with people acting under false pretense. We expect that you will use caution when using the Website. You understand and agree that we do not guarantee the accuracy or legitimacy of any listing, leads, posting, and information by other users. You further agree that we are not liable for any loss of money, goodwill, or reputation, or any special, indirect, or consequential damages arising out of your use of the Website or as a result of any sale, purchase of goods and services with other users of the Website. Dharadhan is not liable in any manner to any third party/User for any content/listing, posted by the Users on the Website.<br>
        Dharadhan reserves, in a manner consistent with reasonable commercial business practices, the right to remove all or any part of the properties and/or other goods and services posted on any part of the Website without prior notice.<br><br>

        <b>15. INDEMNIFICATION</b><br><br>

        You agree to indemnify, defend and hold harmless Dharadhan, its officers, directors, employees and agents from any claim, cost, expense, judgment or other loss incurred due to violation of the terms and conditions contained in this Terms by You.<br><br>

        <b>16. LINKS TO THIRD PARTY SITES</b><br><br>

        The Website may provide links to web sites and access to content, products and services from third parties, including users, advertisers, affiliates and sponsors of the Website. You agree that Dharadhan is not responsible for the availability/accuracy of content including but not limited to opinions, advice, statements and advertisements provided on third party web sites and You shall bear all risks associated with the use of such content and for acting upon such content. You are requested to peruse the policies posted by respective web sites regarding privacy policy and terms of use before usage of the said third party web sites. Dharadhan is not responsible for any loss or damage of any sort You may incur from usage of contents of third party websites. Dharadhan makes no representations or warranties as to the functioning of any third party website. A link to a third party web site from the Website does not constitute endorsement by Dharadhan of the owner of the other site, the content of its site, or its products or services.<br><br>

        <b>17. GOVERNING LAW</b><br><br>

        By accessing the Website you agree that the laws prevailing in India shall be the governing laws in all matters relating to these Terms.<br><br>

        <b>18. JURISDICTION</b><br><br>

        Courts at Jaipur, India alone shall have the exclusive jurisdiction in all matters relating to the use of these Terms, irrespective of the territory and jurisdiction of your access to the Website.<br>
        You agree to inform us if you come across any listing or posting that is offensive or violates our listing policy or infringes any intellectual property rights by sending a mail to info@Dharadhan.com to enable us to keep the Website working efficiently and in a safe manner. We reserve the right to take down any posting, listing or information and or limit or terminate our Services and further take all reasonable technical and legal steps to prevent the misuse of the Website in keeping with the letter and spirit of these Terms. In the event you encounter any problems with the use of our Website or Services you are requested to report the problem by sending an e-mail to info@Dharadhan.com
        The information provided in this Website is based on Dharadhan data which is collected from various publicly known sources viz, websites, documents and maps including Dharadhan’s proprietary data resources, and from the inputs of unidentified individuals. It ought to be considered as a guideline and not as absolutely certain. While care has been taken for groundwork, no responsibility is accepted for the accuracy of whole or any part. This information is absolute property of Dharadhan/Dharadhan Ventures Private Limited). It should not be reproduced in any form, in part or whole, without prior written permission of Dharadhan. The information is provided on an "as is" and "as available" basis. Dharadhan expressly disclaim warranties of any kind, whether express or implied, including, but not limited to, the implied warranties of merchantability, fitness for a particular purpose and non-infringement.
    </p>
</div>
</section>
@endsection
